version: '3.8'
services:
  postgres:
    image: "postgres"
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=base_escola
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  

  pgadmin-compose:
    image: dpage/pgadmin4
    container_name: pdadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "mack@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin123"
    ports:
      - "54321:80"
    depends_on:
      - postgres
