---
- hosts: projeto-mack
  tasks:
  - name: Setup maquina
    ansible.builtin.import_role:
      name: setup_linux
      tasks_from: setup_linux.yaml
    become: yes

  - name: Instalação docker e docker compose
    ansible.builtin.import_role:
      name: setup_docker
      tasks_from: setup_docker.yaml
    become: yes
