- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  
- name: Atualização dos pacotes
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Instalando Docker Compose
  ansible.builtin.shell:
    cmd: >
      curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      && chmod +x /usr/local/bin/docker-compose
  args:
    creates: /usr/local/bin/docker-compose

- name: Start e habilita Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Criação do grupo docker
  ansible.builtin.group:
    name: docker
    state: present

- name: Add usuário da instancia no grupo docker
  ansible.builtin.user:
    name: projeto
    groups: docker
    append: true
